### ISSUE TITLE
Add a favicon to the site

### ISSUE THREAD

**Issue by sarnava1** [gatsbyjs/mdx-deck-theme#7]
We must add a favicon to the site for display in the title bar

**Comment by DSchau** [comment]
Sure - seems reasonable!

**Comment by ayan-b** [comment]
I would like to work on this issue. :smiley:

**Comment by gagandeepp** [comment]
@sarnava1  @DSchau  @ayan-b  this has been fixed ,Please merge the PR
https://github.com/gatsbyjs/mdx-deck-theme/pull/12
